version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-docker
    ports:
    - "5672:5672"
    - "15672:15672"
    volumes:
        - ./dados:/var/lib/rabbitmq/
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=123456
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      
  mongodb:
    image: mongo
    container_name: mongodb-docker
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db

  compass:
    image: mongo-express
    container_name: mongo-compass
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456